### ISSUE TITLE
an uploading error

### ISSUE THREAD

**Issue by hellspector** [jjaychen1e/logseq-plugin-image-uploader#10]
help me.
when uploading this tip jumps out....the picgo setting , obsidin upload works well.
![image](https://user-images.githubusercontent.com/80568889/221216568-02d2b925-fb4a-41f8-b256-32011650d469.png)

logseq version .0.8.17
picgo version :2.3.0

**Comment by jjaychen1e** [comment]
Could you please provide the log messages from the developer console when failed to upload?

BTW, you can toggle the developer console via `View >Toggle Developer Tools`, or `Option-Cmd-i` on Mac, or `Ctrl-Shift-i` on Windows.

**Comment by hellspector** [comment]
> OK.... this is error log..please check.

[upload-error.log](https://github.com/jjaychen1e/logseq-plugin-image-uploader/files/10826145/upload-error.log)

**Comment by hellspector** [comment]
这个是我在obsidian image uploader里面的设置，serve的配置是：http://127.0.0.1:36677/upload，不知道有没有关系。OB是可以用的。
![image](https://user-images.githubusercontent.com/80568889/221236130-1225dceb-bf19-48ae-9fb1-c592d73057ef.png)

**Comment by hellspector** [comment]
Today I tried again. I found the picgo had upload the images. but the logseq plugin didn't get the link of images.

[errorlog.txt](https://github.com/jjaychen1e/logseq-plugin-image-uploader/files/10831346/errorlog.txt)

**Comment by hellspector** [comment]
> Could you please provide the log messages from the developer console when failed to upload?
> 
> BTW, you can toggle the developer console via `View >Toggle Developer Tools`, or `Option-Cmd-i` on Mac, or `Ctrl-Shift-i` on Windows.

the log had upload to the github...please check~~

**Comment by jjaychen1e** [comment]
> > Could you please provide the log messages from the developer console when failed to upload?
> > BTW, you can toggle the developer console via `View >Toggle Developer Tools`, or `Option-Cmd-i` on Mac, or `Ctrl-Shift-i` on Windows.
> 
> the log had upload to the github...please check~~

It's caused by the CORS. It should not happen since we've add the `effect` option in the `manifest.json` (https://github.com/logseq/marketplace#how-to-submit-your-plugin).

I've tested it on my Mac, I got the same issue. I will check how could it happen tomorrow, this may be a bug in the latest version of logseq.

**Comment by hellspector** [comment]
ok thanks 
i don't know.My last version was 0.8.1.2，the plugin didn't work ...0.8.1.5 didn't work.. now logs is the latest version 0.8.1.7...plugin still didnot work.

**Comment by jjaychen1e** [comment]
> ok thanks
> i don't know.My last version was 0.8.1.2，the plugin didn't work ...0.8.1.5 didn't work.. now logs is the latest version 0.8.1.7...plugin still didnot work.

I realize that the reason I got the same issue is that I forgot to set the proxy with my PicGo yesterday. I've tested uploading images using Logseq 0.8.17, PicGo 2.3.1, and the latest version of this plugin (install from the marketplace) on both Mac and Windows, and all images are uploaded by PicGo and inserted in Logseq correctly.

The reason why you get this error is due to CORS. Logseq provides an option for plugins to allow CORS, and I've set that option (`effect`) to true in the marketplace: https://github.com/logseq/marketplace/blob/master/packages/logseq-image-uploader/manifest.json

You can try to verify the plugin's `package.json` is correct in your local system:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/31304335/221503881-1fe6822b-1e81-4521-8024-cad6ff538e7e.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/31304335/221503991-c8c303eb-209f-4ecf-a65c-c04046e4acbc.png">

```JSON
{"name":"logseq-plugin-image-uploader","version":"v0.0.12","main":"dist/index.html","scripts":{"dev":"vite","build":"tsc && vite build"},"dependencies":{"@logseq/libs":"^0.0.1-alpha.33","react":"^17.0.2","react-dom":"^17.0.2","semver":"^7.3.5"},"devDependencies":{"@types/react":"^17.0.33","@types/react-dom":"^17.0.10","@types/semver":"^7.3.9","@vitejs/plugin-react":"1.1.3","typescript":"4.5.4","vite":"2.7.10"},"logseq":{"id":"_jjaychen-logseq-image-uploader","title":"Image Uploader","icon":"./icon.png"},"repo":"JJAYCHEN1e/logseq-plugin-image-uploader","title":"Image Uploader","author":"jjaychen","description":"Upload images with PicGo.","effect":true}
```

At the end of the `package.json`, you should see `"effect":true`. If not, you could try to add this option manually.

**Comment by hellspector** [comment]
I add this option manually and then the problem had gone.
thank you!
cheers.
