### ISSUE TITLE
操作逻辑优化

### ISSUE THREAD

**Issue by larry8916** [jjaychen1e/logseq-plugin-image-uploader#4]
感谢提供logseq的图床插件。

请问，我测试结果表明可以上传图片，但是您的插件不会自动修改远程图片的URL，是我的设设置不对吗？

我对比了Obsidian的这个插件，https://github.com/renmu123/obsidian-image-auto-upload-plugin

它也使用了Picgo 的本地server进行图像上传，但是操作逻辑更为简单：
支持直接将图片从剪贴板粘贴后，直接改为远程连接。

不知道是否可以借鉴一下？

**Comment by jjaychen1e** [comment]
@liuyun16 你好，感谢你的反馈。由于目前的交互逻辑是手动触发上传，所以为了防止重复上传，我过滤掉了所有 URL 图片。关于交互逻辑的优化，初期的设想是支持粘贴后自动触发以及手动触发（为了上传之前已经存在的图片）。由于 Loseq 没有提供监听粘贴事件的的接口，可能考虑通过浏览器接口实现，我会验证可行性。

--------------
Hello, thank you for your feedback. Since the current interaction logic is to manually trigger uploads, in order to prevent repeated uploads, I filtered out all URL pictures. Regarding the optimization of interaction logic, the initial idea is to support automatic triggering after pasting and manual triggering (in order to upload pictures that already existed before). Since Loseq does not provide an interface to monitor pasting events, it may be considered to implement it through the browser interface, and I will verify the feasibility. (Auto translated by Apple Translate)

**Comment by jjaychen1e** [comment]
@liuyun16 增加了自动上传的功能，在 README 中可以找到示例。

--------
Automatic upload feature has been added, and an example can be found in README. (Auto translated by Apple Translate)

**Comment by larry8916** [comment]
感谢，已经测试成功！
现已支持从剪贴板直接上传，替换成远程URL，感谢！
